Search event by keyword
miketully426/AroundTown-Server pull request #8
Opened 2021-12-19 23:39 UTC by mertzjl91

Searches events by keyword.

2021-12-20 00:45 UTC, miketully426 requested changes

2021-12-20 00:45 UTC, miketully426 commented on src/main/java/com/launchcode/AroundTownServer/models/Event.java
> +    public String name;
This should all be private.

2021-12-20 00:45 UTC, miketully426 commented on src/main/java/com/launchcode/AroundTownServer/models/Event.java
> +    public String description;
private!

2021-12-20 00:45 UTC, miketully426 commented on src/main/java/com/launchcode/AroundTownServer/models/Event.java
> +    public String location;
private!

2021-12-20 00:47 UTC, miketully426 commented
I think you forgot to push some commits? There's no code here for searching.

2021-12-28 00:42 UTC, lfallert approved these changes
Tested and working as intended. I did update a couple event fields to have the correct access modifiers and I pushed those changes to this branch.

2021-12-28 20:17 UTC, CNichole726 approved these changes
Looks good to me

2022-01-01 19:07 UTC, closed without merging